In [1]:
from preprocess import get_data
import os

In [2]:
data_dir = '/Users/nakagawaayato/compe/signate_hiroshima/original_data/train'

## 変数を返す

In [3]:
rain, rain_st, tide, tide_st, water, water_st, dam, river_table, river_system_table = get_data(data_dir)

1. データ読み込み
 => complete
2. 3つのデータに前処理 & database化
2191
 => complete
3. 1つのstationに対し値を一列に時系列で並べる
 => complete
4. 河川名、水系名について処理
 => complete
5. 変数を返す

All Complete!!!

In [4]:
water

,date,hour,0,1,2,3,4,5,6,7,...,190,191,192,193,194,195,196,197,198,199
0,0,0,1.64,0.48,-0.07,0.03,-0.08,-0.05,0.5,-0.13,...,4.71,0.47,-0.14,0.77,0.39,0.28,0.54,0.01,0.74,0.15
1,0,1,1.64,0.48,-0.08,0.03,-0.08,-0.05,0.49,-0.58,...,4.71,0.47,-0.14,0.77,0.39,0.28,0.54,0.01,0.75,0.15
2,0,2,1.64,0.48,-0.08,0.03,-0.08,-0.05,0.49,-0.91,...,4.7,0.47,-0.14,0.77,0.39,0.28,0.54,0,0.75,0.15
3,0,3,1.64,0.49,-0.08,0.03,-0.08,-0.05,0.49,-1.07,...,4.7,0.47,-0.14,0.77,0.39,0.28,0.54,0,0.75,0.15
4,0,4,1.64,0.49,-0.08,0.03,-0.08,-0.05,0.49,-1.11,...,4.71,0.47,-0.14,0.77,0.39,0.28,0.54,0,0.75,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52579,2190,19,1.65,0.39,-0.15,-0.03,-0.14,0.15,-0.08,-0.66,...,4.68,0.53,0.47,0.66,NaN,M,0.56,-0.05,0.61,0.24
52580,2190,20,1.63,0.39,-0.15,-0.03,-0.14,0.15,-0.08,-0.57,...,4.68,0.53,0.47,0.66,NaN,M,0.56,-0.05,0.61,0.24
52581,2190,21,1.62,0.39,-0.15,-0.03,-0.14,0.15,-0.08,-0.15,...,4.68,0.53,0.46,0.65,NaN,M,0.56,-0.05,0.61,0.24
52582,2190,22,1.62,0.39,-0.15,-0.03,-0.15,0.14,-0.08,0.15,...,4.68,0.53,0.46,0.63,NaN,M,0.56,-0.06,0.61,0.24
52583,2190,23,1.61,0.39,-0.15,-0.04,-0.15,0.15,-0.08,0.54,...,4.68,0.53,0.46,0.59,NaN,M,0.56,-0.06,0.61,0.24

## directoryに保存

save_dirを指定するとそのフォルダに出来上がった9つのcsvファイルを保存します。

In [4]:
save_dir = '/Users/nakagawaayato/compe/signate_hiroshima/data/temp'

In [5]:
get_data(data_dir, save_dir)

1. データ読み込み
 => complete
2. 3つのデータに前処理 & database化
 => complete
3. 1つのstationに対し値を一列に時系列で並べる
 => complete
4. 河川名、水系名について処理
 => complete
5. 保存

All Complete!!!